name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: Build
        run: go build

      - name: Get current time
        uses: 1466587594/current-time@v1
        id: current-time
        with:
          format: YYYYMMDDHHmm
          utcOffset: "+08:00"

      - name: Get short sha
        uses: benjlevesque/short-sha@v1.1
        id: short-sha
        with:
          length: 6

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: skp-${{ steps.current-time.outputs.formattedTime }}-${{ steps.short-sha.outputs.sha }}
          path: ./skp.exe
