name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: Build
        run: go build

      - name: Get current time
        uses: 1466587594/current-time@v1
        id: current-time
        with:
          format: YYYYMMDDHHmm
          utcOffset: "+08:00"

      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: fgit-amd64-windows-${{ steps.current-time.outputs.formattedTime }}-${{ steps.sha.outputs.sha }}
          path: ./skp.exe
